name = "subtracker-react"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[env.production]
name = "subtracker-react"

# Cloudflare Pages配置
[env.production.build]
command = "npm run build"
output_dir = "dist"

# 环境变量（可选）
[env.production.vars]
REACT_APP_API_URL = "https://api.subtracker.com"
REACT_APP_ENV = "production"

# 开发环境
[env.development]
name = "subtracker-react-dev"

[env.development.vars]
REACT_APP_API_URL = "http://localhost:3001"
REACT_APP_ENV = "development"